elevation_mapping:
  ros__parameters:
    input_sources:
      - left
      - right

    left.type: pointcloud
    left.topic: /Airy_left_point_cloud
    left.queue_size: 1
    left.publish_on_update: true
    left.sensor_processor.type: perfect
        
    right.type: pointcloud
    right.topic: /Airy_right_point_cloud
    right.queue_size: 1
    right.publish_on_update: true
    right.sensor_processor.type: perfect



    map_frame_id: "odom"
    robot_odom_topic: ""
    robot_base_frame_id: "base_link"
    robot_pose_with_covariance_topic: ""
    robot_pose_cache_size: 200
    track_point_frame_id: "base_link"
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: 0.0
