elevation_mapping:
  ros__parameters:
    length_in_x: 100.0
    length_in_y: 100.0
    position_x: 0.0
    position_y: 0.0
    resolution: 0.3
    min_variance: 0.0001
    max_variance: 0.1
    mahalanobis_distance_threshold: 5.0
    multi_height_noise: 0.1
    sensor_processor.ignore_points_above: 2.0
