<?xml version="1.0"?>
<package format="3">
  <name>elevation_mapping_demos</name>
  <version>0.7.4</version>
  <description>Demonstrations for the elevation mapping framework.</description>

  <maintainer email="mwulf@anybotics.com">Maximilian Wulf</maintainer>
  <maintainer email="ynava@anybotics.com">Yoshua Nava</maintainer>
  <author email="pfankhauser@anybotics.com">Péter Fankhauser</author>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rviz2</depend>
  <depend>elevation_mapping</depend>
  <depend>grid_map_visualization</depend>
  <depend>pcl_ros</depend>
  <depend>point_cloud_io</depend>
  <depend>robot_state_publisher</depend>
  <depend>tf2_ros</depend>
  <depend>xacro</depend>
  <depend>python3</depend>
  <depend>rclpy</depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
